
//Keyword list
export const FETCH_KEYWORDS = 'FETCH_KEYWORDS';
export const FETCH_KEYWORDS_FULFILLED = 'FETCH_KEYWORDS_FULFILLED';
export const FETCH_KEYWORDS_REJECTED = 'FETCH_KEYWORDS_REJECTED';
export const RESET_KEYWORDS = 'RESET_KEYWORDS';

//Keyword paginated list
export const FETCH_PAGINATED_KEYWORDS = 'FETCH_PAGINATED_KEYWORDS';
export const FETCH_PAGINATED_KEYWORDS_FULFILLED = 'FETCH_PAGINATED_KEYWORDS_FULFILLED';
export const FETCH_PAGINATED_KEYWORDS_REJECTED = 'FETCH_PAGINATED_KEYWORDS_REJECTED';
export const RESET_PAGINATED_KEYWORDS = 'RESET_PAGINATED_KEYWORDS';

//Keyword Total Count
export const FETCH_KEYWORDS_COUNT = 'FETCH_KEYWORDS_COUNT';
export const FETCH_KEYWORDS_COUNT_FULFILLED = 'FETCH_KEYWORDS_COUNT_FULFILLED';
export const FETCH_KEYWORDS_COUNT_REJECTED = 'FETCH_KEYWORDS_COUNT_REJECTED';
export const RESET_KEYWORDS_COUNT = 'RESET_KEYWORDS_COUNT';

//Fetch keyword
export const FETCH_KEYWORD = 'FETCH_KEYWORD';
export const FETCH_KEYWORD_FULFILLED = 'FETCH_KEYWORD_FULFILLED';
export const FETCH_KEYWORD_REJECTED = 'FETCH_KEYWORD_REJECTED';
export const RESET_ACTIVE_KEYWORD = 'RESET_ACTIVE_KEYWORD';

//Create new keyword
export const CREATE_KEYWORD = 'CREATE_KEYWORD';
export const CREATE_KEYWORD_FULFILLED = 'CREATE_KEYWORD_FULFILLED';
export const CREATE_KEYWORD_REJECTED = 'CREATE_KEYWORD_REJECTED';
export const RESET_NEW_KEYWORD = 'RESET_NEW_KEYWORD';

//Update site
export const UPDATE_SITE = 'UPDATE_SITE';
export const UPDATE_SITE_FULFILLED = 'UPDATE_SITE_FULFILLED';
export const UPDATE_SITE_REJECTED = 'UPDATE_SITE_REJECTED';
export const RESET_UPDATED_SITE = 'RESET_UPDATED_SITE';

//Validate keyword fields like Title, Categries on the server
export const VALIDATE_KEYWORD_FIELDS = 'VALIDATE_KEYWORD_FIELDS';
export const VALIDATE_KEYWORD_FIELDS_FULFILLED = 'VALIDATE_KEYWORD_FIELDS_FULFILLED';
export const VALIDATE_KEYWORD_FIELDS_REJECTED = 'VALIDATE_KEYWORD_FIELDS_REJECTED';
export const RESET_KEYWORD_FIELDS = 'RESET_KEYWORD_FIELDS';

//Delete keyword
export const DELETE_KEYWORD = 'DELETE_KEYWORD';
export const DELETE_KEYWORD_FULFILLED = 'DELETE_KEYWORD_FULFILLED';
export const DELETE_KEYWORD_REJECTED = 'DELETE_KEYWORD_REJECTED';
export const RESET_DELETED_KEYWORD = 'RESET_DELETED_KEYWORD';
