
//Site list
export const FETCH_SITES = 'FETCH_SITES';
export const FETCH_SITES_FULFILLED = 'FETCH_SITES_FULFILLED';
export const FETCH_SITES_REJECTED = 'FETCH_SITES_REJECTED';
export const RESET_SITES = 'RESET_SITES';

//Fetch site
export const FETCH_SITE = 'FETCH_SITE';
export const FETCH_SITE_FULFILLED = 'FETCH_SITE_FULFILLED';
export const FETCH_SITE_REJECTED = 'FETCH_SITE_REJECTED';
export const RESET_ACTIVE_SITE = 'RESET_ACTIVE_SITE';

//Create new site
export const CREATE_SITE = 'CREATE_SITE';
export const CREATE_SITE_FULFILLED = 'CREATE_SITE_FULFILLED';
export const CREATE_SITE_REJECTED = 'CREATE_SITE_REJECTED';
export const RESET_NEW_SITE = 'RESET_NEW_SITE';

//Update site
export const UPDATE_SITE = 'UPDATE_SITE';
export const UPDATE_SITE_FULFILLED = 'UPDATE_SITE_FULFILLED';
export const UPDATE_SITE_REJECTED = 'UPDATE_SITE_REJECTED';
export const RESET_UPDATED_SITE = 'RESET_UPDATED_SITE';

//Validate site fields like Title, Categries on the server
export const VALIDATE_SITE_FIELDS = 'VALIDATE_SITE_FIELDS';
export const VALIDATE_SITE_FIELDS_FULFILLED = 'VALIDATE_SITE_FIELDS_FULFILLED';
export const VALIDATE_SITE_FIELDS_REJECTED = 'VALIDATE_SITE_FIELDS_REJECTED';
export const RESET_SITE_FIELDS = 'RESET_SITE_FIELDS';

//Delete site
export const DELETE_SITE = 'DELETE_SITE';
export const DELETE_SITE_FULFILLED = 'DELETE_SITE_FULFILLED';
export const DELETE_SITE_REJECTED = 'DELETE_SITE_REJECTED';
export const RESET_DELETED_SITE = 'RESET_DELETED_SITE';
