#%RAML 1.0 DataType

    properties:
      siteId: number
      keyword: string
      translation: string
      checksum: string
      tracking: number
      deleted: number
      device: object
      market: object