#%RAML 1.0 DataType

    properties:
      title: string
      url: string
      tracking: integer
      dropWWWPrefix: integer
      dropDirectories: integer
      contactEmail: string
      treatNonRankingAs: number
      nonRankingValue: number
