#%RAML 1.0 DataType

    properties:
      siteId: number
      crawlDate: date
      globalAggregateSV: number
      globalAverageSV: number
      regionalAggregateSV: number
      regionalAverageSV: number