#%RAML 1.0 DataType

    properties:
      siteId: number
      crawlDate: date
      backLinks: integer
      indexed: integer
      pageRank: integer
      nonRankingValue: string
      totalKeywords: number
      trackedKeywords: number
      untrackedKeywords: number
      uniqueKeywords: number
      nonUniqueKeywords: number
      rankingKeywords: number
      googleRankingKeywords: number
      googleBaseRankingKeywords: number
      googleTopTenKeywords: number
      googleAverage: number
      googleBaseAverage: number