#%RAML 1.0 DataType

    properties:
      siteId: number
      crawlDate: date
      one: number
      two: number
      three: number
      four: number
      five: number
      sixToTen: number
      elevenToTwenty: number
      twentyOneToThirty: number
      thirtyOneToForty: number
      fortyOneToFifty: number
      fiftyOneToHundred: number
      nonRanking: number