#%RAML 1.0 DataType

    properties:
      tagId: number
      crawlDate: date
      totalKeywords: number
      trackedKeywords: number
      rankingKeywords: number
      googleRankingKeywords: number
      googleBaseRankingKeywords: number
      googleTopTenKeywords: number
      googleAverage: number
      googleBaseAverage: number