spring:
  datasource:
    url: jdbc:mysql://serpstat:3306/serpstat
    username: serp-stat
    password: statserp
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
        hbm2ddl:
          import_files: